export default {
    CREATE_UDP_CLIENT: "CREATE_UDP_CLIENT",
    CREATE_UDP_SERVER: "CREATE_UDP_SERVER",
    CREATE_TCP_SERVER: "CREATE_TCP_SERVER",
    CREATE_TCP_CLIENT: "CREATE_TCP_CLIENT",
    CHANGE_REMOVE_SPACE: "CHANGE_REMOVE_SPACE",
    CHANGE_HEX_MODEL: "CHANGE_HEX_MODEL",
    CHANGE_MAIN_SOCKE: "CHANGE_MAIN_SOCKE",
    set_main_socket: "SET_MAIN_SOCKET",
    add_sockets: "ADD_SOCKETS",
    remove_sockets: "REMOVE_SOCKETS",
    set_msg: "SET_MSG",
    set_sockets: 'SET_SOCKETS'
}